#ifndef __ws_autonomous_prog_h_
#define __ws_autonomous_prog_h_

#define AUTO_PROG_2_SAFE_TIMER   (160)

typedef enum
{
  AP_SWPR_STATE_DONE
} ApSwprState;

typedef enum
{
  AP_GRBR_STATE_LOWER_ARM,
  AP_GRBR_STATE_RELEASE_TUBE,
  AP_GRBR_STATE_RAISE_ARM,
  AP_GRBR_STATE_DONE
} ApGrbrState;

typedef enum
{
  AP_HKSQR_STATE_DRIVE_TO_RACK,
  AP_HKSQR_STATE_PAUSE_AT_RACK,
  AP_HKSQR_STATE_LOWER_ARM,
  AP_HKSQR_STATE_RELEASE_TUBE,
  AP_HKSQR_STATE_GO_HOME_RELEASING,
  AP_HKSQR_STATE_GO_HOME_IN_STORAGE,
  AP_HKSQR_STATE_GRAB_HP,
  AP_HKSQR_STATE_DONE
} ApHksqrState;

typedef enum
{
  AP_SWPRL_STATE_TURN_CRAB_90_LEFT,
  AP_SWPRL_STATE_DRIVE_LEFT,
  AP_SWPRL_STATE_PAUSE_AFTER_LEFT,
  AP_SWPRL_STATE_DRIVE_RIGHT,
  AP_SWPRL_STATE_PAUSE_AFTER_RIGHT,
  AP_SWPRL_STATE_RAISE_ARM,
  AP_SWPRL_STATE_DONE
} ApSwprlState;

typedef enum
{
  AP_SWPRR_STATE_TURN_CRAB_90_LEFT,
  AP_SWPRR_STATE_DRIVE_LEFT,
  AP_SWPRR_STATE_PAUSE_AFTER_LEFT,
  AP_SWPRR_STATE_DRIVE_RIGHT,
  AP_SWPRR_STATE_PAUSE_AFTER_RIGHT,
  AP_SWPRR_STATE_RAISE_ARM,
  AP_SWPRR_STATE_DONE
} ApSwprrState;


typedef enum
{
  AP_SONR_CW_STATE_RAISE_ARM_INIT,
  AP_SONR_CW_STATE_DRIVE_TO_RACK,
  AP_SONR_CW_STATE_PAUSE_AT_RACK,
  AP_SONR_CW_STATE_CRAB_AT_RACK,
  AP_SONR_CW_STATE_FIND_SPIDER,
  AP_SONR_CW_STATE_PAUSE_AFTER_FIND,
  AP_SONR_CW_STATE_DRIVE_TO_SPIDER,
  AP_SONR_CW_STATE_BLIND_DRIVE_TO_SPIDER,
  AP_SONR_CW_STATE_PAUSE_AT_SPIDER,
  AP_SONR_CW_STATE_LOWER_ARM,
  AP_SONR_CW_STATE_RELEASE_TUBE,
  AP_SONR_CW_STATE_GO_HOME_RELEASE,
  AP_SONR_CW_STATE_GO_HOME_STORAGE,
  AP_SONR_CW_STATE_RAISE_ARM,
  AP_SONR_CW_STATE_DONE
} ApSonrCwState;

#if 0
typedef enum
{
  AP_SONR_CCW_STATE_RAISE_ARM_INIT,
  AP_SONR_CCW_STATE_DRIVE_TO_RACK,
  AP_SONR_CCW_STATE_PAUSE_AT_RACK,
  AP_SONR_CCW_STATE_CRAB_AT_RACK,
  AP_SONR_CCW_STATE_FIND_SPIDER,
  AP_SONR_CCW_STATE_PAUSE_AFTER_FIND,
  AP_SONR_CCW_STATE_DRIVE_TO_SPIDER,
  AP_SONR_CCW_STATE_PAUSE_AT_SPIDER,
  AP_SONR_CCW_STATE_LOWER_ARM,
  AP_SONR_CCW_STATE_RELEASE_TUBE,
  AP_SONR_CCW_STATE_GO_HOME_RELEASE,
  AP_SONR_CCW_STATE_GO_HOME_STORAGE,
  AP_SONR_CCW_STATE_RAISE_ARM,
  AP_SONR_CCW_STATE_DONE
} ApSonrCcwState;
#else
typedef enum
{
  AP_SONR_CCW_STATE_INIT,
  AP_SONR_CCW_STATE_PLACE_TUBE,
  AP_SONR_CCW_STATE_DONE
} ApSonrCcwState;
#endif

typedef enum
{
  AP_SONR_SIDE_CCW_STATE_INIT,
  AP_SONR_SIDE_CCW_STATE_PLACE_TUBE,
  AP_SONR_SIDE_CCW_STATE_DONE
} ApSonrSideCcwState;

typedef enum
{
  AP_SONR_SIDE_CW_STATE_INIT,
  AP_SONR_SIDE_CW_STATE_PLACE_TUBE,
  AP_SONR_SIDE_CW_STATE_DONE
} ApSonrSideCwState;


typedef enum
{
  AP_SONR_STATE_RAISE_ARM_INIT,
  AP_SONR_STATE_DRIVE_TO_RACK,
  AP_SONR_STATE_PAUSE_AT_RACK,
  AP_SONR_STATE_CRAB_AT_RACK,
  AP_SONR_STATE_FIND_SPIDER,
  AP_SONR_STATE_PAUSE_AFTER_FIND,
  AP_SONR_STATE_DRIVE_TO_SPIDER,
  AP_SONR_STATE_BLIND_DRIVE_TO_SPIDER,
  AP_SONR_STATE_PAUSE_AT_SPIDER,
  AP_SONR_STATE_LOWER_ARM,
  AP_SONR_STATE_RELEASE_TUBE,
  AP_SONR_STATE_DRIVE_RELEASE,
  AP_SONR_STATE_GO_HOME_STORAGE,
  AP_SONR_STATE_RAISE_ARM,
  AP_SONR_STATE_DONE_FAIL,
  AP_SONR_STATE_DONE
} ApSonrState;

#endif /* __ws_autonomous_prog_h_ */
